import { view } from './view_projects.js';

const more_info_text = {
    "p1": "<div><p>Objectif : développer une méthode de tri automatique pour des dépêches</p> <p>Compétence du Programme National : réaliser un développement d’application et optimiser des applications</p><ul><li>Unité d'enseignement 1 : Réaliser un développement<ul><li>Apprentissage critique 1 : implémenter des conceptions simples </li><li>Apprentissage critique 2 : Élaborer des conceptions simples</li><li>Apprentissage critique 3 : Faire des essais et évaluer leurs résultats en regard des spécifications </li></ul></li><li>Unité d'enseignement 2 : Optimiser des applications<ul><li>Apprentissage critique 1 : analyser un problème avec méthode (découpage en éléments algorithmiques simples, structure de données…) </li><li>Apprentissage critique 2 : comparer des algorithmes pour des problèmes classiques (tris simples, recherche…)</li><li>Apprentissage critique 3 : formaliser et mettre en œuvre des outils mathématiques pour l’informatique</li></ul></li></ul><p>Nous avons fait un programme permettant de déterminer pour chaque dépêche la catégorie associé d'abord à partir de lexique crée par nous-même puis généré automatiquement. Nous avons ensuite optimisé le programme de manière à diminuer le temps de classement des dépêches.</p><p>J'ai travaillé sur la partie du tri manuelle et j'ai également fait le compte rendu en anglais.</p></div>",
    "p2": "<div><p>Objectif : Installation d'un poste de travail avec configuration d'un IDE</p><p>Compétence du Programme National : administrer des systèmes informatiques communicants complexes </p><ul><li>Unité d'enseignement 3 : administrer des systèmes<ul><li>Apprentissage critique 1 : identifier les différents composants (matériels et logiciels) d’un système numérique</li><li>Apprentissage critique 2 : utiliser les fonctionnalités de base d’un système multitâches / multi utilisateurs</li><li>Apprentissage critique 3 : installer et configurer un système d’exploitation et des outils de développement</li></ul></li></ul><p>J'ai installé un poste de travail sous la distribution linux Debian 12 et installé plusieurs logiciels tels que netbrains pour le développement et l'environnement virtuel Java. J'ai également réalisé une carte mentale expliquant comment le faire.</p></div>",
    "p3": "<div><p>Objectif : création et gestion d'une base de données sur le Titanic</p><p>Compétence du Programme National : gérer des données de l’information </p><ul><li>Unité d'enseignement 4 : Gérer des données<ul><li>Apprentissage critique 1 : mettre à jour et interroger une base de données relationnelle (en requêtes directes ou à travers une application)</li><li>Apprentissage critique 3 :concevoir une base de données relationnelle à partir d’un cahier des charges</li></ul></li></ul><p>Nous avons crée une base de données sur le Titanic en SQL en commençant par récolter des informations utiles pour avoir une idée des relations, puis un schéma puis en la réalisant sur un poste de travail et nous avons également crée des tests pour vérifier si la base fonctionnait ainsi que des requêtes spécifiques et un bilan.</p><p>J'ai fais la partie création de la base de données et une partie des tests pour vérifier son bon fonctionnement.</p></div>",
    "p4": "<div><p>Objectif : réaliser un site web qui convient aux 3ème en recherche de stage</p><p>Compétence du Programme National : conduire un projet et collaborer au sein d’une équipe informatique</p><ul><li>Unité d'enseignement 5 : conduire un projet<ul><li>Apprentissage critique 1 : appréhender les besoins du client et de l’utilisateur</li><li>Apprentissage critique 2 : mettre en place les outils de gestion de projet</li></ul></li><li>Unité d'enseignement 6 : travailler en équipe<ul><li>Apprentissage critique 1 : appréhender l’écosystème numérique</li><li>Apprentissage critique 4 : acquérir les compétences interpersonnelles pour travailler en équipe</li></ul></li></ul><p>Nous avons récolté des informations sur IBM et placé tout cela dans un recueil de besoins. Nous avons par la suite développé une maquette d'un site web institutionnelle puis nous l'avons réalisé en HTML et CSS tout en faisant en sorte qu'il soit compréhensible pour des 3èmes en recherche de stage. Nous nous sommes également auto-évalué sur certains critères au sein du projet.</p><p>J'ai collecté la plupart des informations sur leur secteur économique, réalisé une partie des pages de la maquette et ait fait la plupart du code HTML du site final.</p></div>",
    "p5": "<div><p>Objectif : nettoyer et analyser une base de données</p><p>Compétence du Programme National : Gérer des données de l'information</p><ul><li>Unité d'enseignement 4 : Gérer des données<ul><li>Apprentissage critique 1 : mettre à jour et interroger une base de données relationnelle (en requêtes directes ou à travers une application)</li><li>Apprentissage critique 2 : visualiser des données</li><li>Apprentissage critique 3 :concevoir une base de données relationnelle à partir d’un cahier des charges</li></ul></li></ul><p>Nous avons crée un code en SQL pour une base de données de produits alimentaires afin d'en extraire les produits possédant le tag \"biscuit-and-cakes\" et étant vendu aux États-Unis. Nous en avons fais un rapport en anglais étudiant le nutriscore avec plusieurs graphiques en R markdown.</p><p>Je me suis occupé de faire les graphiques et le code SQL pour extraire les données.</p></div>",
    "p6": "",
    "p7": "",
};

let last_click = null;

view.articles.forEach((article) => {
    article.addEventListener("click", function () {
        if(last_click == article.id){
            view.articleMoreInfo.style.visibility = "hidden";
        }else{
            view.articleMoreInfo.style.visibility = "visible";
            view.articleMoreInfo.innerHTML = more_info_text[article.id];
            last_click = article.id;
        }
    })
});